name: first-github-action
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  write-to-console:
    name: Write to console
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello world!'
